### ISSUE TITLE
Throws Fatal Error

### ISSUE THREAD

**Issue by 19peaches** [texthtml/whoops-pimple#2]
I've installed with composer and added to my Pimple container as instructed.

My Container extends Pimple.

```php
$this->register(new \WhoopsPimple\WhoopsServiceProvider);
```
`Fatal error: Call to a member function attach() on null`

Maybe I'm missing something, but on line 58 it seems you're calling the `whoops` object that hasn't yet been created.

```php
$container['whoops']->$method($e);
```
Any help would be appreciated.

**Comment by mathroc** [comment]
Hi!

I just made a very simple test : 

```php
<?php

include_once 'vendor/autoload.php';

$container = new \Pimple\Container;
$container->register(new \WhoopsPimple\WhoopsServiceProvider);

$f = function() {
	throw new Exception("Error Processing Request", 1);
};

$f();
```

and it's working as expected. Can you show me an example that reproduce the error you're having?

**Comment by 19peaches** [comment]
I did show you the error that's produced.

Anytime the whoops object is called the error I referenced is shown.

No worries, I wrote my own service and it's working fine.
